-- Recriação limpa das tabelas do projeto Casamento no Supabase/Postgres
-- ATENÇÃO: este script APAGA as tabelas atuais do schema public deste projeto Supabase
-- Use somente se você ainda não inseriu dados no Supabase ou se quer recomeçar do zero

begin;

create extension if not exists pgcrypto;

-- Limpeza de objetos antigos/parciais
DROP TRIGGER IF EXISTS trg_payments_sync_paid ON public.payments;
DROP FUNCTION IF EXISTS public.trg_payments_sync_paid();
DROP FUNCTION IF EXISTS public.sync_entity_paid(text, integer);

DROP TABLE IF EXISTS public.payments CASCADE;
DROP TABLE IF EXISTS public.selected_suppliers CASCADE;
DROP TABLE IF EXISTS public.supplier_services CASCADE;
DROP TABLE IF EXISTS public.suppliers CASCADE;
DROP TABLE IF EXISTS public.services CASCADE;
DROP TABLE IF EXISTS public.wedding_settings CASCADE;

-- Tabelas principais
CREATE TABLE public.services (
  id integer generated by default as identity PRIMARY KEY,
  name varchar(255) NOT NULL,
  category varchar(100) NOT NULL,
  value numeric(10,2) NOT NULL,
  paid numeric(10,2) NOT NULL DEFAULT 0.00,
  due_date date NULL,
  notes text NULL,
  created_at timestamptz NULL DEFAULT now()
);

CREATE TABLE public.suppliers (
  id integer generated by default as identity PRIMARY KEY,
  name varchar(255) NOT NULL,
  category varchar(100) NOT NULL,
  price numeric(10,2) NOT NULL,
  paid numeric(10,2) NOT NULL DEFAULT 0.00,
  description text NULL,
  notes text NULL,
  created_at timestamptz NULL DEFAULT now()
);

CREATE TABLE public.supplier_services (
  id integer generated by default as identity PRIMARY KEY,
  supplier_id integer NULL REFERENCES public.suppliers(id) ON DELETE CASCADE,
  service_name varchar(255) NOT NULL
);

CREATE TABLE public.selected_suppliers (
  id integer generated by default as identity PRIMARY KEY,
  category varchar(100) NOT NULL,
  supplier_id integer NULL REFERENCES public.suppliers(id) ON DELETE SET NULL
);

CREATE INDEX idx_selected_suppliers_supplier_id
  ON public.selected_suppliers (supplier_id);

CREATE UNIQUE INDEX uq_selected_suppliers_category
  ON public.selected_suppliers (category);

CREATE TABLE public.payments (
  id integer generated by default as identity PRIMARY KEY,
  entity_type text NOT NULL CHECK (entity_type IN ('service', 'supplier')),
  entity_id integer NOT NULL,
  amount numeric(10,2) NOT NULL CHECK (amount >= 0),
  payment_method varchar(50) NOT NULL,
  payment_date date NOT NULL,
  description text NULL,
  receipt_number varchar(100) NULL,
  status varchar(50) NOT NULL DEFAULT 'completed',
  created_at timestamptz NULL DEFAULT now()
);

CREATE INDEX idx_payments_entity_lookup
  ON public.payments (entity_type, entity_id);

CREATE TABLE public.wedding_settings (
  id integer PRIMARY KEY,
  couple_name varchar(255) NULL,
  wedding_date date NULL,
  guest_count integer NULL DEFAULT 0,
  budget_total numeric(12,2) NULL DEFAULT 0.00,
  theme varchar(255) NULL,
  location varchar(255) NULL
);

-- Funções e trigger para sincronizar total pago
CREATE OR REPLACE FUNCTION public.sync_entity_paid(p_entity_type text, p_entity_id integer)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  total_paid numeric(10,2);
BEGIN
  SELECT COALESCE(SUM(amount), 0)
    INTO total_paid
    FROM public.payments
   WHERE entity_type = p_entity_type
     AND entity_id = p_entity_id
     AND status = 'completed';

  IF p_entity_type = 'service' THEN
    UPDATE public.services
       SET paid = total_paid
     WHERE id = p_entity_id;
  ELSIF p_entity_type = 'supplier' THEN
    UPDATE public.suppliers
       SET paid = total_paid
     WHERE id = p_entity_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_payments_sync_paid()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM public.sync_entity_paid(OLD.entity_type, OLD.entity_id);
    RETURN OLD;
  ELSIF TG_OP = 'UPDATE' THEN
    IF OLD.entity_type <> NEW.entity_type OR OLD.entity_id <> NEW.entity_id THEN
      PERFORM public.sync_entity_paid(OLD.entity_type, OLD.entity_id);
    END IF;
    PERFORM public.sync_entity_paid(NEW.entity_type, NEW.entity_id);
    RETURN NEW;
  ELSE
    PERFORM public.sync_entity_paid(NEW.entity_type, NEW.entity_id);
    RETURN NEW;
  END IF;
END;
$$;

CREATE TRIGGER trg_payments_sync_paid
AFTER INSERT OR UPDATE OR DELETE ON public.payments
FOR EACH ROW
EXECUTE FUNCTION public.trg_payments_sync_paid();

-- RLS aberta para uso simples via GitHub Pages sem backend
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.selected_suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wedding_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "open_services" ON public.services
FOR ALL TO anon, authenticated
USING (true) WITH CHECK (true);

CREATE POLICY "open_suppliers" ON public.suppliers
FOR ALL TO anon, authenticated
USING (true) WITH CHECK (true);

CREATE POLICY "open_supplier_services" ON public.supplier_services
FOR ALL TO anon, authenticated
USING (true) WITH CHECK (true);

CREATE POLICY "open_selected_suppliers" ON public.selected_suppliers
FOR ALL TO anon, authenticated
USING (true) WITH CHECK (true);

CREATE POLICY "open_payments" ON public.payments
FOR ALL TO anon, authenticated
USING (true) WITH CHECK (true);

CREATE POLICY "open_wedding_settings" ON public.wedding_settings
FOR ALL TO anon, authenticated
USING (true) WITH CHECK (true);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

commit;
